import React, { useState, useMemo } from 'react';
import {
  BookmarkCheck,
  Plus,
  Trash2,
} from 'lucide-react';
import type { TrackedBet } from '../types/nba';

interface BetTrackerTabProps {
  trackedBets: TrackedBet[];
  onUpdateBetStatus: (betId: string, status: 'PENDING' | 'WON' | 'LOST' | 'PUSH') => void;
  onUpdateBetUnits: (betId: string, units: number) => void;
  onDeleteBet: (betId: string) => void;
  onClearCompleted: () => void;
  onAddNewCustomBet: (bet: Omit<TrackedBet, 'id' | 'timestamp'>) => void;
}

export const BetTrackerTab: React.FC<BetTrackerTabProps> = ({
  trackedBets,
  onUpdateBetStatus,
  onUpdateBetUnits,
  onDeleteBet,
  onClearCompleted,
  onAddNewCustomBet,
}) => {
  const [statusFilter, setStatusFilter] = useState<'ALL' | 'PENDING' | 'RESOLVED'>('ALL');
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Form for custom manual bet
  const [newMatchup, setNewMatchup] = useState('');
  const [newPickType, setNewPickType] = useState<'UNDER' | 'OVER'>('UNDER');
  const [newLine, setNewLine] = useState('224.5');
  const [newModelProj, setNewModelProj] = useState('214.0');
  const [newUnits, setNewUnits] = useState('1.0');
  const [newOdds, setNewOdds] = useState('-110');

  // Performance calculations
  const stats = useMemo(() => {
    const total = trackedBets.length;
    const pending = trackedBets.filter((b) => b.status === 'PENDING').length;
    const won = trackedBets.filter((b) => b.status === 'WON').length;
    const lost = trackedBets.filter((b) => b.status === 'LOST').length;
    const push = trackedBets.filter((b) => b.status === 'PUSH').length;

    const resolved = won + lost;
    const winRate = resolved > 0 ? (won / resolved) * 100 : 0;

    let netUnits = 0;
    let totalRisked = 0;

    trackedBets.forEach((b) => {
      if (b.status === 'WON') {
        netUnits += b.units * 0.909;
        totalRisked += b.units;
      } else if (b.status === 'LOST') {
        netUnits -= b.units;
        totalRisked += b.units;
      }
    });

    const roi = totalRisked > 0 ? (netUnits / totalRisked) * 100 : 0;

    return {
      total,
      pending,
      won,
      lost,
      push,
      winRate,
      netUnits,
      totalRisked,
      roi,
    };
  }, [trackedBets]);

  const filteredBets = useMemo(() => {
    return trackedBets.filter((b) => {
      if (statusFilter === 'PENDING') return b.status === 'PENDING';
      if (statusFilter === 'RESOLVED') return b.status !== 'PENDING';
      return true;
    });
  }, [trackedBets, statusFilter]);

  const handleCreateCustom = (e: React.FormEvent) => {
    e.preventDefault();
    const lineVal = parseFloat(newLine);
    const projVal = parseFloat(newModelProj);
    const unitsVal = parseFloat(newUnits) || 1.0;

    if (!newMatchup || isNaN(lineVal) || isNaN(projVal)) {
      alert('Please fill out the matchup and valid numbers.');
      return;
    }

    onAddNewCustomBet({
      matchId: `custom_${Date.now()}`,
      date: new Date().toISOString().slice(0, 10),
      matchup: newMatchup,
      pickType: newPickType,
      targetLine: lineVal,
      modelProjection: projVal,
      edge: newPickType === 'UNDER' ? lineVal - projVal : projVal - lineVal,
      units: unitsVal,
      odds: newOdds || '-110',
      status: 'PENDING',
    });

    setIsModalOpen(false);
    setNewMatchup('');
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-white dark:bg-[#0c1220] border border-slate-200/90 dark:border-[#1c2438] rounded-2xl p-5 shadow-xs transition-colors duration-200">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-blue-50 dark:bg-emerald-500/10 text-blue-700 dark:text-emerald-400 border border-blue-200 dark:border-emerald-500/20">
              <BookmarkCheck className="h-6 w-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white m-0">
                Quantitative Bet Portfolio &amp; Record Tracker
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400 m-0 mt-0.5">
                Track and grade your Over/Under positions generated by the model. Automatically persists to your local device.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsModalOpen(true)}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 dark:bg-amber-500 dark:hover:bg-amber-400 text-white dark:text-zinc-950 font-semibold dark:font-bold text-xs shadow-xs transition-all cursor-pointer"
            >
              <Plus className="h-4 w-4" />
              <span>Log Manual Pick</span>
            </button>
            {stats.won + stats.lost > 0 && (
              <button
                onClick={onClearCompleted}
                className="px-3 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-medium transition-colors cursor-pointer border border-slate-200 dark:border-transparent"
              >
                Clear Resolved
              </button>
            )}
          </div>
        </div>
      </div>

      {/* KPI Stats Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {/* Card 1: Win Rate */}
        <div className="bg-white dark:bg-[#0c1220] border border-slate-200/90 dark:border-[#1c2438] rounded-2xl p-4 shadow-xs transition-colors duration-200">
          <div className="text-xs text-slate-500 dark:text-slate-400 font-medium uppercase tracking-wider">
            Resolved Win Rate
          </div>
          <div className="text-3xl font-black text-emerald-700 dark:text-emerald-400 font-mono mt-1">
            {stats.winRate.toFixed(1)}%
          </div>
          <div className="text-[11px] text-slate-500 dark:text-slate-400 mt-1 font-mono">
            {stats.won}W - {stats.lost}L {stats.push > 0 ? `(${stats.push}P)` : ''}
          </div>
        </div>

        {/* Card 2: Net Units */}
        <div className="bg-white dark:bg-[#0c1220] border border-slate-200/90 dark:border-[#1c2438] rounded-2xl p-4 shadow-xs transition-colors duration-200">
          <div className="text-xs text-slate-500 dark:text-slate-400 font-medium uppercase tracking-wider">
            Net Units (ROI)
          </div>
          <div
            className={`text-3xl font-black font-mono mt-1 ${
              stats.netUnits >= 0 ? 'text-emerald-700 dark:text-emerald-400' : 'text-rose-700 dark:text-rose-400'
            }`}
          >
            {stats.netUnits >= 0 ? `+${stats.netUnits.toFixed(2)}u` : `${stats.netUnits.toFixed(2)}u`}
          </div>
          <div className="text-[11px] text-slate-500 dark:text-slate-400 mt-1 font-mono">
            ROI: <strong className={stats.roi >= 0 ? 'text-emerald-700 dark:text-emerald-400' : 'text-rose-700 dark:text-rose-400'}>{stats.roi.toFixed(1)}%</strong>
          </div>
        </div>

        {/* Card 3: Active Pending */}
        <div className="bg-white dark:bg-[#0c1220] border border-slate-200/90 dark:border-[#1c2438] rounded-2xl p-4 shadow-xs transition-colors duration-200">
          <div className="text-xs text-slate-500 dark:text-slate-400 font-medium uppercase tracking-wider">
            Pending Wagers
          </div>
          <div className="text-3xl font-black text-blue-700 dark:text-amber-400 font-mono mt-1">
            {stats.pending}
          </div>
          <div className="text-[11px] text-slate-500 dark:text-slate-400 mt-1">
            Awaiting final regulation score
          </div>
        </div>

        {/* Card 4: Total Tracked */}
        <div className="bg-white dark:bg-[#0c1220] border border-slate-200/90 dark:border-[#1c2438] rounded-2xl p-4 shadow-xs transition-colors duration-200">
          <div className="text-xs text-slate-500 dark:text-slate-400 font-medium uppercase tracking-wider">
            Total Tracked Picks
          </div>
          <div className="text-3xl font-black text-slate-900 dark:text-white font-mono mt-1">
            {stats.total}
          </div>
          <div className="text-[11px] text-slate-500 dark:text-slate-400 mt-1">
            Across current session
          </div>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center justify-between">
        <div className="flex items-center bg-slate-100 dark:bg-[#090d16] p-1 rounded-xl border border-slate-200 dark:border-[#1c2438] text-xs">
          <button
            onClick={() => setStatusFilter('ALL')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-colors cursor-pointer ${
              statusFilter === 'ALL'
                ? 'bg-white dark:bg-slate-800 text-slate-900 dark:text-amber-400 font-bold shadow-2xs'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            All Positions ({trackedBets.length})
          </button>
          <button
            onClick={() => setStatusFilter('PENDING')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-colors cursor-pointer ${
              statusFilter === 'PENDING'
                ? 'bg-white dark:bg-slate-800 text-slate-900 dark:text-amber-400 font-bold shadow-2xs'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            Active Pending ({stats.pending})
          </button>
          <button
            onClick={() => setStatusFilter('RESOLVED')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-colors cursor-pointer ${
              statusFilter === 'RESOLVED'
                ? 'bg-white dark:bg-slate-800 text-slate-900 dark:text-amber-400 font-bold shadow-2xs'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            Graded Results ({stats.won + stats.lost + stats.push})
          </button>
        </div>
      </div>

      {/* Bets List */}
      {filteredBets.length === 0 ? (
        <div className="bg-white dark:bg-[#0f1422] border border-slate-200 dark:border-[#1c2438] rounded-xl p-12 text-center text-slate-500 dark:text-slate-400 text-xs shadow-xs transition-colors duration-200">
          <BookmarkCheck className="h-8 w-8 text-slate-400 dark:text-slate-600 mx-auto mb-2" />
          <p className="font-semibold text-slate-900 dark:text-white text-sm">No tracked bets yet</p>
          <p className="text-slate-500 dark:text-slate-400 mt-1">
            Browse the <strong>Picks Board</strong> tab and click <strong>"+ Track"</strong> to monitor positions here, or click <strong>"Log Manual Pick"</strong>.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredBets.map((bet) => {
            const isWon = bet.status === 'WON';
            const isLost = bet.status === 'LOST';
            const isPending = bet.status === 'PENDING';
            const isUnder = bet.pickType === 'UNDER';

            return (
              <div
                key={bet.id}
                className="bg-white dark:bg-[#0f1422] border border-slate-200 dark:border-[#1c2438] rounded-xl p-4 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4 transition-all hover:border-slate-300 dark:hover:border-slate-700"
              >
                {/* Matchup & Pick Info */}
                <div className="flex items-center gap-3.5">
                  <div
                    className={`h-11 w-11 rounded-xl flex items-center justify-center font-bold text-xs shrink-0 border ${
                      isUnder
                        ? 'bg-emerald-50 dark:bg-emerald-950/80 border-emerald-200 dark:border-emerald-500/40 text-emerald-800 dark:text-emerald-400'
                        : 'bg-rose-50 dark:bg-rose-950/80 border-rose-200 dark:border-rose-500/40 text-rose-800 dark:text-rose-400'
                    }`}
                  >
                    {isUnder ? 'UNDER' : 'OVER'}
                  </div>

                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-slate-900 dark:text-white text-sm">{bet.matchup}</span>
                      <span className="text-[11px] text-slate-500 dark:text-slate-400 font-mono">{bet.date}</span>
                    </div>

                    <div className="flex items-center gap-3 text-xs mt-1 font-mono">
                      <span className="text-slate-700 dark:text-slate-300">
                        Pick: <strong className="text-slate-900 dark:text-white">{bet.pickType} {bet.targetLine}</strong>
                      </span>
                      <span className="text-slate-300 dark:text-slate-600">•</span>
                      <span className="text-blue-700 dark:text-amber-400">
                        Model: {bet.modelProjection.toFixed(1)}
                      </span>
                      <span className="text-slate-300 dark:text-slate-600">•</span>
                      <span className="text-slate-600 dark:text-amber-300">
                        Edge: {bet.edge > 0 ? `+${bet.edge.toFixed(1)}` : bet.edge.toFixed(1)} pts
                      </span>
                    </div>
                  </div>
                </div>

                {/* Units, Status Switcher & Delete */}
                <div className="flex items-center flex-wrap gap-3 self-end sm:self-center">
                  {/* Units Input */}
                  <div className="flex items-center gap-1.5 bg-slate-50 dark:bg-[#090d16] px-2.5 py-1 rounded-lg border border-slate-200 dark:border-[#1c2438] text-xs">
                    <span className="text-slate-500 dark:text-slate-400 text-[11px]">Units:</span>
                    <input
                      type="number"
                      step="0.5"
                      min="0.1"
                      value={bet.units}
                      onChange={(e) => {
                        const val = parseFloat(e.target.value);
                        if (!isNaN(val) && val > 0) onUpdateBetUnits(bet.id, val);
                      }}
                      className="w-12 bg-transparent text-slate-900 dark:text-white font-mono font-bold text-center focus:outline-none"
                    />
                    <span className="text-slate-500">u</span>
                  </div>

                  {/* Status Buttons */}
                  <div className="flex items-center bg-slate-100 dark:bg-[#090d16] p-1 rounded-xl border border-slate-200 dark:border-[#1c2438] text-xs">
                    <button
                      onClick={() => onUpdateBetStatus(bet.id, 'PENDING')}
                      className={`px-2 py-1 rounded-lg text-[11px] font-semibold transition-colors cursor-pointer ${
                        isPending ? 'bg-blue-600 text-white shadow-2xs' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                      }`}
                    >
                      Pending
                    </button>
                    <button
                      onClick={() => onUpdateBetStatus(bet.id, 'WON')}
                      className={`px-2 py-1 rounded-lg text-[11px] font-semibold transition-colors cursor-pointer ${
                        isWon ? 'bg-emerald-600 text-white shadow-2xs' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                      }`}
                    >
                      Won
                    </button>
                    <button
                      onClick={() => onUpdateBetStatus(bet.id, 'LOST')}
                      className={`px-2 py-1 rounded-lg text-[11px] font-semibold transition-colors cursor-pointer ${
                        isLost ? 'bg-rose-600 text-white shadow-2xs' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                      }`}
                    >
                      Lost
                    </button>
                  </div>

                  {/* Delete Button */}
                  <button
                    onClick={() => onDeleteBet(bet.id)}
                    className="p-1.5 text-slate-400 hover:text-rose-600 dark:hover:text-rose-400 transition-colors cursor-pointer rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"
                    title="Remove bet"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Manual Add Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 dark:bg-[#090d16]/80 backdrop-blur-xs animate-fade-in">
          <div className="bg-white dark:bg-[#0f1422] border border-slate-200 dark:border-[#1c2438] rounded-xl max-w-md w-full p-6 shadow-xl relative text-slate-900 dark:text-white">
            <h3 className="text-base font-bold text-slate-900 dark:text-white mb-3">Log Custom Position</h3>
            <form onSubmit={handleCreateCustom} className="space-y-4 text-xs">
              <div>
                <label className="text-slate-700 dark:text-slate-300 font-semibold block mb-1">Matchup</label>
                <input
                  type="text"
                  placeholder="e.g. New York Knicks @ Boston Celtics"
                  value={newMatchup}
                  onChange={(e) => setNewMatchup(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-[#090d16] border border-slate-200 dark:border-[#1c2438] rounded-xl px-3 py-2 text-slate-900 dark:text-white focus:outline-none focus:bg-white dark:focus:bg-[#090d16] focus:border-blue-500 dark:focus:border-amber-400"
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-slate-700 dark:text-slate-300 font-semibold block mb-1">Pick Type</label>
                  <select
                    value={newPickType}
                    onChange={(e) => setNewPickType(e.target.value as any)}
                    className="w-full bg-slate-50 dark:bg-[#090d16] border border-slate-200 dark:border-[#1c2438] rounded-xl px-3 py-2 text-slate-900 dark:text-white focus:outline-none focus:bg-white dark:focus:bg-[#090d16] focus:border-blue-500 dark:focus:border-amber-400"
                  >
                    <option value="UNDER">UNDER</option>
                    <option value="OVER">OVER</option>
                  </select>
                </div>

                <div>
                  <label className="text-slate-700 dark:text-slate-300 font-semibold block mb-1">Target Total Line</label>
                  <input
                    type="number"
                    step="0.5"
                    value={newLine}
                    onChange={(e) => setNewLine(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-[#090d16] border border-slate-200 dark:border-[#1c2438] rounded-xl px-3 py-2 text-slate-900 dark:text-white font-mono focus:outline-none focus:bg-white dark:focus:bg-[#090d16] focus:border-blue-500 dark:focus:border-amber-400"
                    required
                  />
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="text-slate-700 dark:text-slate-300 font-semibold block mb-1">Model Total</label>
                  <input
                    type="number"
                    step="0.5"
                    value={newModelProj}
                    onChange={(e) => setNewModelProj(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-[#090d16] border border-slate-200 dark:border-[#1c2438] rounded-xl px-3 py-2 text-slate-900 dark:text-white font-mono focus:outline-none focus:bg-white dark:focus:bg-[#090d16] focus:border-blue-500 dark:focus:border-amber-400"
                    required
                  />
                </div>
                <div>
                  <label className="text-slate-700 dark:text-slate-300 font-semibold block mb-1">Units (Wager)</label>
                  <input
                    type="number"
                    step="0.5"
                    value={newUnits}
                    onChange={(e) => setNewUnits(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-[#090d16] border border-slate-200 dark:border-[#1c2438] rounded-xl px-3 py-2 text-slate-900 dark:text-white font-mono focus:outline-none focus:bg-white dark:focus:bg-[#090d16] focus:border-blue-500 dark:focus:border-amber-400"
                  />
                </div>
                <div>
                  <label className="text-slate-700 dark:text-slate-300 font-semibold block mb-1">Odds</label>
                  <input
                    type="text"
                    value={newOdds}
                    onChange={(e) => setNewOdds(e.target.value)}
                    className="w-full bg-slate-50 dark:bg-[#090d16] border border-slate-200 dark:border-[#1c2438] rounded-xl px-3 py-2 text-slate-900 dark:text-white font-mono focus:outline-none focus:bg-white dark:focus:bg-[#090d16] focus:border-blue-500 dark:focus:border-amber-400"
                  />
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2 border-t border-slate-200 dark:border-[#1c2438]">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700 cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 dark:bg-amber-500 dark:hover:bg-amber-400 text-white dark:text-zinc-950 font-semibold dark:font-bold cursor-pointer shadow-xs"
                >
                  Save Bet
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
export default BetTrackerTab;
